name: "GitHub Classroom Autograding Results handler"
description: "Integrate your CS class with GitHub using GitHub Classroom"
inputs:
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}
  runners:
    description: 'Comma-separated list of step ids'
    required: true

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'  # 自动缓存 npm 依赖

      - name: Install dependencies
        run: npm install --silent

      - name: Build project
        run: npm run build

runs:
  using: "node20"
  main: "dist/main.js"
